damianvtran/local-operator-ui

- src/renderer/src/api/local-operator/models-api.ts
- src/renderer/src/components/hosting/hosting-model-manifest.ts
- src/renderer/src/components/hosting/model-select.tsx
- src/renderer/src/store/models-store.ts
This PR introduces a new "recommended" flag for models, enhancing the user experience by highlighting models that are widely used and well-regarded by the community. This feature is implemented across the application, from the API to the UI, ensuring a consistent and intuitive experience.
- **API Updates:** The `ModelInfo` type in `src/renderer/src/api/local-operator/models-api.ts` now includes a `recommended` boolean field. The `listModels` API endpoint has been updated to support sorting by the `recommended` field.
- **Data Model Updates:** The `Model` type in `src/renderer/src/components/hosting/hosting-model-manifest.ts` now includes a `recommended` boolean field.
- **UI Enhancements:** The `ModelSelect` component in …
> Add "recommended" flag to models

- .env.template
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- package.json
This PR includes changes related to release automation, version bumping, and the addition of a "recommended" flag for models.
- Updated the version to `0.1.2-beta.3` in `package.json`.
- Modified the publish workflow to use a keychain for code signing and to attach artifacts to the release in `.github/workflows/publish.yml`.
- Related: #...
- Improved release automation process.
- The changes were tested by running the existing unit tests and integration tests.
- Specific scenarios validated include:
- The version number is correctly updated.
- The code signing process works as expected.
If applicable, please attach screenshots that illustrate the changes or new features.
> Implement CD release automation

- .github/workflows/install-scripts-check.yml
- package.json
- src/main/backend/scripts/linux-install-script.sh
- src/main/backend/scripts/macos-install-script.sh
- src/main/backend/scripts/windows-install-script.ps1
This PR introduces a new GitHub Actions workflow to check the installation scripts on different platforms, updates the UI version to `0.1.2-beta.5`
- Added a new GitHub Actions workflow to check the installation scripts on different platforms.
- Updated the UI version to `0.1.2-beta.5`.
- Modified the installation scripts to improve cross-platform compatibility.
- Related: None
- Improves the reliability of the installation process by adding automated checks.
- Enables cross-platform support for Linux
- Minor update to the prompts.
- The new workflow will automatically test the installation scripts on Linux, macOS, and Windows.
- Manual testing was performed on Windows and macOS.
> Multi-platform install script fixes and enhancements

- README.md
- package.json
- src/main/index.ts
- src/renderer/src/api/local-operator/config-api.ts
- src/renderer/src/components/agents/agents-page.tsx
- src/renderer/src/components/agents/agents-sidebar.tsx
- src/renderer/src/components/agents/general-settings.tsx
- src/renderer/src/components/chat/chat-page.tsx
- src/renderer/src/components/common/agent-options-menu.tsx
- src/renderer/src/components/installer/logo-section.tsx
- src/renderer/src/components/settings/system-prompt.tsx
- src/renderer/src/hooks/use-job-polling.ts
- src/renderer/src/hooks/use-system-prompt.ts
This PR improves the user interface and user experience by adding a chat button to the agent management page and agent sidebar, handling the case where no system prompt exists, and adding error details to job polling. It also fixes bugs by handling the 204 No Content response for the system prompt and updating the tagline.
- Updated the tagline in `README.md`.
- Updated the version to `0.1.2-beta.6` in `package.json`.
- Added application menu in `src/main/index.ts`.
- Handled 204 No Content response for system prompt in `src/renderer/src/api/local-operator/config-api.ts`.
- Added chat button to agent management page in `src/renderer/src/components/agents/agents-page.tsx`.
- Added chat button to agent sidebar in `src/renderer/src/components/agents/agents-sidebar.tsx`.
- Added chat option …
> Improve UI and fix bugs

- package.json
- src/renderer/index.html
- src/renderer/installer.html
- src/renderer/src/api/local-operator/static-api.ts
- src/renderer/src/api/local-operator/types.ts
- src/renderer/src/components/chat/chat-content.tsx
- src/renderer/src/components/chat/chat-page.tsx
- src/renderer/src/components/chat/loading-indicator.tsx
- src/renderer/src/components/chat/message-item/index.tsx
- src/renderer/src/components/chat/message-item/types.ts
- src/renderer/src/components/chat/message-item/video-attachment.tsx
- src/renderer/src/components/chat/messages-view.tsx
- src/renderer/src/components/hosting/model-select.tsx
- src/renderer/src/components/navigation/sidebar-navigation.tsx
- src/renderer/src/hooks/use-clear-agent-conversation.ts
- src/renderer/src/hooks/use-job-polling.ts
- src/renderer/src/store/ui-preferences-store.ts
This PR introduces video attachment support, improves the loading indicator, persists the sidebar state, and adds a throttle to the model refresh function.
Key improvements and modifications:
*   Video attachment support: Users can now send and receive video attachments in the chat interface.
*   Improved loading indicator: The loading indicator now displays the current execution details and code snippet.
*   Persisted sidebar state: The sidebar state (expanded or collapsed) is now persisted using the UI preferences store.
*   Throttled model refresh: The model refresh function in the hosting settings is now throttled to prevent multiple rapid calls.
- Related: #...
- No breaking changes were introduced.
- No dependency updates were included in this PR.
- There are no known performance or …
> feat: Add video attachment support and UI improvements

- package.json
- src/renderer/src/components/agents/agents-sidebar.tsx
- src/renderer/src/components/chat/attachments-preview.tsx
- src/renderer/src/components/chat/chat-page.tsx
- src/renderer/src/components/chat/chat-sidebar.tsx
- src/renderer/src/components/chat/loading-indicator.tsx
- src/renderer/src/components/chat/markdown-renderer.tsx
- src/renderer/src/components/chat/message-input.tsx
- src/renderer/src/components/chat/message-item/background-block.tsx
- src/renderer/src/components/chat/messages-view.tsx
- src/renderer/src/components/navigation/sidebar-navigation.tsx
- src/renderer/src/hooks/use-message-input.ts
- src/renderer/src/hooks/use-scroll-to-bottom.ts
- yarn.lock
This PR introduces several theme adjustments and new features to enhance the user experience and functionality of the Local Operator UI.
- Updated the version number to `0.2.3` and added dependencies for `katex`, `rehype-katex`, `remark-gfm`, and `remark-math` to support LaTeX rendering in markdown.
- Added a `selected` prop to the `AgentAvatar` styled component in `src/renderer/src/components/agents/agents-sidebar.tsx` and `src/renderer/src/components/chat/chat-sidebar.tsx` to change the background and text color when an agent is selected.
- Added support for video attachments in `src/renderer/src/components/chat/attachments-preview.tsx`, including a new `AttachmentVideo` styled component and logic to determine if a file is a video.
- Reduced the threshold for the `useScrollToBottom` …
> Theme Adjustments and Updates

- package.json
- src/main/backend/backend-installer.ts
- src/main/backend/backend-service.ts
- src/main/backend/scripts/windows-install-script.ps1
- src/main/index.ts
- src/main/update-service.ts
- src/renderer/src/hooks/use-route-params.ts
- src/renderer/src/main.tsx
- src/renderer/src/utils/path-utils.ts
This PR improves the Windows setup and installation process for the local-operator-ui.
*   **Backend Installer:** Added pyenv-win paths to the backend installer to improve Python environment detection.
*   **Windows Installation Script:** Modified the Windows installation script to handle pyenv-win and virtual environment creation more robustly.
*   **Executable Checks:** Added checks for the local-operator executable in the virtual environment to ensure proper installation.
*   **Backend Service:** Improved the backend service startup and shutdown process on Windows, including better process termination and environment variable handling.
*   **Routing:** Switched to HashRouter in the renderer to handle routing in the packaged app.
*   **Path Utilities:** Added utility functions for …
> feat: Improve Windows setup and installation process

- package.json
- src/renderer/src/components/onboarding/steps/search-api-step.tsx
- src/renderer/src/components/settings/credential-manifest.tsx
- Updates the package version to 0.3.1.
- Fixes a typo in the SearchApiStep component, correcting the order of credential keys.
- Adds support for FAL API key in the credential manifest, enabling image generation capabilities for agents.
- Related: #N/A
Describe the impact of these changes on the codebase:
- This change introduces a new dependency on FAL for image generation.
- There are no breaking changes.
- There are no known performance or security implications.
- The changes were tested manually by verifying the functionality of the image generation feature.
- Specific scenarios validated include:
- Successful image generation with a valid FAL API key.
- Proper handling of missing or invalid FAL API key.
- No automated tests were added or …
> feat: Add image generation support

- build/LICENSE.txt
- package.json
- src/main/backend/backend-service.ts
- src/main/index.ts
- src/main/update-service.ts
- Adds a `build/LICENSE.txt` file containing the End User License Agreement (EULA) for the installer.
- Updates the package version to 0.3.4 in `package.json`. (Note: This seems like a downgrade, please verify)
- Modifies the NSIS configuration in `package.json` to enable desktop shortcut creation, start menu shortcut creation, and deletion of app data on uninstall, and sets the license file.
- Implements auto-update functionality in `src/main/update-service.ts` and related files.
- Adds a flag to track auto-updating status in `src/main/backend/backend-service.ts` to prevent error dialogs during shutdown.
- Related: #N/A
Describe the impact of these changes on the codebase:
- This change adds a license agreement to the installer.
- This change …
> feat: Implement Windows auto-update and add license agreement

- package.json
- src/main/index.ts
- Updates the package version to 0.3.5 in `package.json`.
- Removes the check for auto-update process before quitting the app in `src/main/index.ts`.
- Related: #N/A
Describe the impact of these changes on the codebase:
- This change updates the package version.
- This change modifies the app quitting behavior.
- There are no breaking changes.
- The changes were tested manually by:
- Building the application for Windows.
- Verifying that the package version is updated.
- Testing the app quitting behavior to ensure that the app quits correctly.
- No automated tests were added or updated in this PR.
If applicable, please attach screenshots that illustrate the changes or new features.
> feat: Update package version and modify app quitting behavior

- package.json
- src/renderer/src/components/chat/chat-content.tsx
- src/renderer/src/components/chat/chat-page.tsx
- src/renderer/src/components/chat/chat-sidebar.tsx
- src/renderer/src/components/chat/message-item/action-highlight.tsx
- src/renderer/src/components/chat/message-item/background-block.tsx
- src/renderer/src/components/chat/message-item/index.tsx
- src/renderer/src/components/chat/message-item/message-container.tsx
- src/renderer/src/components/chat/message-item/message-controls.tsx
- src/renderer/src/components/chat/message-item/message-paper.tsx
- src/renderer/src/components/chat/message-item/types.ts
- src/renderer/src/components/chat/messages-view.tsx
- src/renderer/src/components/common/error-boundary.tsx
- src/renderer/src/main.tsx
- src/renderer/src/utils/env-utils.ts
- Implements several styling and UI improvements to the chat interface.
- Adds a new `env-utils.ts` file to check if the application is running in development mode.
- Modifies `chat-content.tsx` and `chat-page.tsx` to only show the "raw" tab in development mode.
- Updates `chat-sidebar.tsx` to improve the layout and styling of the agent list.
- Modifies `action-highlight.tsx` and `background-block.tsx` to improve the styling of action highlights and background blocks.
- Adds a new `message-controls.tsx` file to implement message control buttons (e.g. copy button).
- Modifies `message-paper.tsx` to improve the styling of message papers.
- Updates `messages-view.tsx` to improve the layout of messages.
- Modifies `error-boundary.tsx` to only show …
> feat: Improve chat interface styles

- package.json
- src/renderer/src/api/local-operator/websocket-api.ts
- src/renderer/src/components/chat/chat-page.tsx
- src/renderer/src/components/hosting/model-select.tsx
- src/renderer/src/hooks/use-scroll-to-bottom.ts
- src/renderer/src/hooks/use-websocket-message.ts
- Updated `package.json` to bump version from 0.4.0 to 0.4.1.
- Modified Electron builder targets to generate **universal** architecture DMG and ZIP builds for better compatibility with Apple Silicon and Intel Macs.
- Enhanced chat message handling in `chat-page.tsx`:
- Integrated `useConfig()` hook to fetch global defaults.
- Added logic to resolve hosting/model defaults from global config if agent-specific values are unset or "default".
- Cleaned up comments and streamlined error handling.
- Improved WebSocket client (`websocket-api.ts`):
- Removed redundant console error logs during reconnect failures.
- Suppressed verbose error output during reconnect attempts.
- Refactored model selection component (`model-select.tsx`):
- Improved `renderOption` function with better key handling.
- …
> Universal Mac build, chat config fallback, and UI improvements

- package.json
- src/renderer/src/components/chat/attachments-preview.tsx
- src/renderer/src/components/chat/chat-content.tsx
- src/renderer/src/components/chat/chat-sidebar.tsx
- src/renderer/src/components/chat/message-input.tsx
- src/renderer/src/components/chat/messages-view.tsx
- src/renderer/src/components/common/agent-options-menu.tsx
- Redesigned the chat input area with a new layout, styling, and suggestion chips to improve usability and onboarding.
- Added a set of default message suggestions to help users get started quickly.
- The message input now conditionally renders based on loading state and message presence, improving UX during initial load.
- Refactored the chat sidebar to add a **Clear Conversation** feature with confirmation modal, allowing users to reset conversations easily.
- Improved empty and loading states in the message view for a cleaner, more responsive experience.
- Updated component styling for better responsiveness, accessibility, and maintainability.
- Removed redundant elements and cleaned up code across chat-related components.
- Related: #...
- Significantly improves the chat UI's …
> Chat UI redesign with suggestions and clear conversation feature

- src/main/index.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/components/hosting/hosting-select.tsx
- src/renderer/src/components/hosting/model-select.tsx
- src/renderer/src/features/chat/directory-indicator.tsx
- src/renderer/src/features/chat/message-item/image-attachment.tsx
- src/renderer/src/features/chat/message-item/index.tsx
- src/renderer/src/features/chat/message-item/invalid-attachment.tsx
- src/renderer/src/features/chat/message-item/message-paper.tsx
- src/renderer/src/features/chat/message-item/streaming-message.tsx
- src/renderer/src/features/chat/message-item/types.ts
- src/renderer/src/features/chat/message-item/video-attachment.tsx
- src/renderer/src/features/chat/messages-view.tsx
- src/renderer/src/hooks/use-scroll-to-bottom.ts
- src/renderer/src/shared/components/common/agent-options-menu.tsx
This PR improves the user experience around model selection and working directory management in the UI.
- Fix unpredictable scrolling by refactoring the scroll to bottom hook and general behaviour.  Uses a fixed anchor in the scroll container in the messages view
- Modified `HostingSelect` component to automatically refresh the model list when the hosting provider is changed.
- Refactored and simplified the model refresh logic in `ModelSelect` to use a simple debounce, removing previous complex throttling and retry limits.
- Added IPC handlers in the main process (`select-directory`, `get-home-directory`) for native directory selection and retrieving the user's home path.
- Exposed `selectDirectory` and `getHomeDirectory` functions via the preload script …
> feat: Improve model selection refresh and add directory handling

- src/main/index.ts
- src/main/store.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/api/radient/auth-api.ts
- src/renderer/src/api/radient/index.ts
- src/renderer/src/api/radient/types.ts
- src/renderer/src/features/chat/chat-page.tsx
- src/renderer/src/features/chat/loading-indicator.tsx
- src/renderer/src/features/chat/message-input.tsx
- src/renderer/src/features/chat/message-item/message-paper.tsx
- src/renderer/src/features/chat/messages-view.tsx
- src/renderer/src/features/onboarding/onboarding-modal.tsx
- src/renderer/src/features/onboarding/steps/radient-signin-step.tsx
- src/renderer/src/hooks/use-conversation-messages.ts
- src/renderer/src/hooks/use-message-input.ts
- src/renderer/src/hooks/use-oidc-auth.ts
- src/renderer/src/hooks/use-radient-auth.ts
- src/renderer/src/hooks/use-radient-user-query.ts
- src/renderer/src/hooks/use-scroll-to-bottom.ts
- src/renderer/src/utils/session-store.ts
This PR implements the necessary infrastructure for handling OAuth refresh tokens, specifically for the Radient authentication flow. It allows the application to obtain new access tokens without requiring the user to log in again frequently.
- Updated `StoreData` type and session storage logic (`main/index.ts`, `main/store.ts`) to store `radient_access_token` and `radient_refresh_token` separately, replacing the old `radient_jwt`.
- Modified preload script (`preload/index.ts`, `preload/index.d.ts`) to align `getSession` and `storeSession` with the new token structure.
- Added `refreshToken` function to `api/radient/auth-api.ts` to call the `/v1/auth/token` endpoint.
- Added `revokeToken` function to `api/radient/auth-api.ts` to call the `/v1/auth/revoke` endpoint.
- …
> feat: Implement OAuth refresh token handling

- biome.json
- src/main/backend/backend-installer.ts
- src/main/backend/backend-service.ts
- src/main/index.ts
- src/renderer/src/features/agents/chat-settings.tsx
- src/renderer/src/features/agents/general-settings.tsx
- src/renderer/src/features/agents/security-settings.tsx
- src/renderer/src/features/agents/system-prompt-settings.tsx
- src/renderer/src/features/chat/chat-options-utils.tsx
- src/renderer/src/hooks/use-connectivity-status.ts
- src/renderer/src/hooks/use-streaming-message.ts
- src/renderer/src/shared/components/common/autocomplete-field.tsx
- src/renderer/src/shared/components/common/editable-field.tsx
- Addressed unused variables identified by the linter.
- [Specific files and examples of fixes will be added after reviewing the diff output.]
- Related: #...
- Improves code cleanliness and reduces potential for confusion by removing unused variables.
- Resolves linting warnings related to unused variables.
- No known breaking changes to existing functionality.
- No known performance or security implications.
- Verified that the application still builds and runs after the changes.
- Confirmed that linting checks for unused variables now pass (or the specific warnings addressed by this branch are resolved).
- Ran existing automated tests to ensure no regressions.
N/A
- This PR addresses unused variables in the codebase to improve code cleanliness and pass linting checks.
> Address unused variables

- biome.json
- src/main/backend/backend-service.ts
- src/main/backend/index.ts
- src/main/update-service.ts
- src/renderer/src/api/local-operator/index.ts
- src/renderer/src/api/local-operator/websocket-api.ts
- src/renderer/src/api/radient/index.ts
- src/renderer/src/components/auth/index.ts
- src/renderer/src/components/hosting/index.ts
- src/renderer/src/components/navigation/collapsible-app-logo.tsx
- src/renderer/src/components/navigation/index.ts
- src/renderer/src/features/chat/components/attachments-preview.tsx
- src/renderer/src/features/chat/components/message-item/file-attachment.tsx
- src/renderer/src/features/chat/components/message-item/image-attachment.tsx
- src/renderer/src/features/chat/components/message-item/invalid-attachment.tsx
- src/renderer/src/features/chat/components/message-item/video-attachment.tsx
- src/renderer/src/features/installer/index.ts
- src/renderer/src/features/onboarding/index.ts
- src/renderer/src/hooks/index.ts
- src/renderer/src/providers/auth/index.ts
- src/renderer/src/providers/feature-flags/index.ts
- src/renderer/src/shared/components/common/index.ts
- Updated `biome.json` to include new performance linting rules (`noReExportAll`, `useTopLevelRegex`).
- Moved regex constants to the top level in `backend-service.ts`, `update-service.ts`, `websocket-api.ts`, `collapsible-app-logo.tsx`, and various attachment components for performance optimization as suggested by the linter.
- Changed `export * from` statements to named exports in several index files (`src/main/backend/index.ts`, `src/renderer/src/api/local-operator/index.ts`, `src/renderer/src/api/radient/index.ts`, `src/renderer/src/components/auth/index.ts`, `src/renderer/src/components/hosting/index.ts`, `src/renderer/src/components/navigation/index.ts`, `src/renderer/src/features/installer/index.ts`, `src/renderer/src/features/onboarding/index.ts`, …
> Refactor: Update linter configuration and code structure

- package.json
- src/renderer/src/features/agents/components/agents-page.tsx
- src/renderer/src/features/agents/components/agents-sidebar.tsx
- src/renderer/src/features/chat/components/chat-page.tsx
- src/renderer/src/features/chat/components/chat-sidebar.tsx
- src/renderer/src/features/chat/utils/chat-utilities.tsx
- src/renderer/src/shared/api/local-operator/agents-api.ts
- src/renderer/src/shared/components/hosting/model-select.tsx
- src/renderer/src/shared/hooks/use-agents.ts
- src/renderer/src/shared/hooks/use-message-input.ts
- src/renderer/src/shared/hooks/use-streaming-message.ts
This PR includes bug fixes, refactoring, and feature enhancements focused on agent management, UI consistency, and model refresh reliability.
- Refactored agent list and selection logic in AgentsPage and AgentsSidebar for improved stability and performance.
- Improved model list refreshing logic in HostingSelect and ModelSelect components.
- Proper handling of "auto" tag to be under "Radient" section with "radient" hosting 
- Updated branding and author information in package.json.
- Enhanced UI styling for agent management components.
- Bumped version in package.json to 0.5.2.
- NA
- Refactors agent data handling hooks and components, which might require minor adjustments in consuming code if not already aligned.
- No dependency updates identified in the diff.
- Performance: Refactored …
> fix: agent management, UI consistency, and model refresh improvements

- package.json
- src/renderer/src/features/agents/components/general-settings.tsx
- src/renderer/src/features/chat/components/message-item/background-block.tsx
- src/renderer/src/shared/api/local-operator/types.ts
- Adds support for the `DELEGATE` action type in the UI, including new iconography and labels for delegated tasks.
- Updates project branding in `package.json` (author, copyright, and keywords).
- Bumps version to 0.6.0.
- Minor UI improvements in agent settings and general settings components.
Link any related issue or feature request (e.g., closes #123):
- Related: #... _(Please link if applicable)_
- No breaking changes.
- The UI now visually distinguishes delegated actions with a new icon and label.
- Branding is updated to reflect current project ownership.
- No dependency updates.
- No security or performance implications.
- Manual testing of the chat UI to confirm the `DELEGATE` action type displays the correct icon and label.
- Verified …
> feat: support for agent to agent protocol

- package.json
- src/renderer/src/features/agent-hub/components/agent-card.tsx
- src/renderer/src/features/agent-hub/components/comments-section.tsx
- src/renderer/src/features/agent-hub/hooks/use-agent-comments-query.ts
- src/renderer/src/features/chat/components/loading-indicator.tsx
- src/renderer/src/features/chat/components/message-input.tsx
- src/renderer/src/features/chat/components/message-item/error-block.tsx
- src/renderer/src/features/chat/components/message-item/log-block.tsx
- src/renderer/src/features/chat/components/message-item/output-block.tsx
- src/renderer/src/features/settings/components/settings-section-card.tsx
- src/renderer/src/shared/api/radient/agents-api.ts
- src/renderer/src/shared/hooks/use-message-input.ts
- src/renderer/src/shared/store/conversation-input-store.ts
- Refactors message input to use a new Zustand store for robust per-conversation input persistence and up-arrow history navigation.
- Improves Agent Hub experience for signed-out users: comments can now be viewed by anyone, and like/favourite actions are disabled with tooltips if not authenticated.
- Enhances the loading indicator to display stdout, stderr, and logging output blocks during code execution.
- Adds a new Zustand store (`conversation-input-store.ts`) for managing input state and history.
- Updates styling for output, error, and log blocks to improve scroll behavior.
- Refines agent selection and sidebar logic for better stability and performance.
- Adds directory selection and home directory IPC handlers for improved UX.
- Updates …
> feat: improve agent hub for signed-out users, robust message input history, and UI/branding updates

- package.json
- src/main/backend/backend-service.ts
- src/main/index.ts
- src/main/update-service.ts
- src/renderer/src/features/chat/components/message-item/file-attachment.tsx
- src/renderer/src/features/chat/components/message-item/index.tsx
- src/renderer/src/features/onboarding/components/onboarding-modal.tsx
- src/renderer/src/features/onboarding/components/steps/create-agent-step.tsx
- src/renderer/src/features/onboarding/components/steps/radient-choice-step.tsx
- src/renderer/src/features/settings/components/credential-card.tsx
- src/renderer/src/features/settings/components/credential-dialog.tsx
- src/renderer/src/features/settings/components/settings-page.tsx
- src/renderer/src/features/settings/components/system-prompt.tsx
- src/renderer/src/shared/components/common/check-for-updates-button.tsx
- src/renderer/src/shared/components/common/slider-setting.tsx
- src/renderer/src/shared/components/common/update-notification.tsx
- src/renderer/src/shared/hooks/use-job-polling.ts
- src/renderer/src/shared/store/deferred-updates-store.ts
- Adds configurable shutdown timeouts and improved process management in the backend service.
- Refactors update service with robust resource cleanup and safer event handling.
- Implements new IPC handlers for directory selection and home directory access.
- Refactors agent management UI for better stability and performance.
- Updates onboarding, settings, and credential dialogs for improved UX and modern styling.
- Refactors deferred update store to handle UI/backend updates separately and adds hydration state.
-NA
- No breaking changes.
- Improved reliability and maintainability for auto-updater and backend management.
- UI/UX improvements for agent management and credential handling.
- No dependency updates.
- No known security or performance …
> feat: auto-updater improvements, UI/branding updates, and agent management enhancements

- package.json
- src/renderer/src/app.tsx
- src/renderer/src/features/schedules/components/agent-id-input-dialog.tsx
- src/renderer/src/features/schedules/components/schedule-form-dialog.tsx
- src/renderer/src/features/schedules/components/schedule-list-item.tsx
- src/renderer/src/features/schedules/components/schedules-page.tsx
- src/renderer/src/features/schedules/hooks/use-schedules-queries.ts
- src/renderer/src/shared/api/local-operator/index.ts
- src/renderer/src/shared/api/local-operator/schedules-api.ts
- src/renderer/src/shared/api/local-operator/types.ts
- src/renderer/src/shared/components/navigation/sidebar-navigation.tsx
- src/renderer/src/shared/hooks/use-route-params.ts
This PR introduces a new 'Schedules' page to the Local Operator UI.
- Addition of a new route for `/schedules`.
- New components for managing schedules:
- `SchedulesPage`: The main page to display and manage schedules.
- `ScheduleFormDialog`: A dialog for creating and editing schedule details, including agent selection, prompt, interval, unit, start/end times, and active status.
- `AgentIdInputDialog`: A dialog to input an Agent ID, likely used when creating a schedule without pre-selecting an agent.
- Version bump in `package.json` from 0.7.5 to 0.8.0.
- Related: #[Your Issue Number Here if Applicable]
- This is a new feature and should not introduce breaking changes to existing functionality.
- No direct dependency updates were noted in the provided diff, but new …
> feat: Add Schedules page and related UI components

- package.json
- src/renderer/src/app.tsx
- src/renderer/src/features/chat/components/messages-view.tsx
- src/renderer/src/shared/api/local-operator/types.ts
- src/renderer/src/shared/components/common/low-credits-dialog.stories.tsx
- src/renderer/src/shared/components/common/low-credits-dialog.tsx
- src/renderer/src/shared/hooks/use-low-credits-dialog.ts
- src/renderer/src/shared/store/low-credits-store.ts
This PR introduces several user experience improvements to the Local Operator UI:
- **Low Credits Dialog:** Adds a new dialog to notify users when their Radient credits are running low. This includes:
- New `LowCreditsDialog` component and supporting hook/store (`useLowCreditsDialog`, `useLowCreditsStore`).
- Storybook stories for the dialog.
- Integration into the main app layout.
- **Informational Message Dividers in Chat:** Updates the chat interface to display informational messages (such as agent import notifications) as styled dividers within the message flow, improving readability.
- Adds a new `ExecutionType` of `"info"` to support this.
- Updates `MessagesView` to render these messages distinctly.
- **Version Bump:** Updates `package.json` version from `0.9.0` to `0.9.1`.
- …
> feat: Add low credits dialog and info message dividers to improve UX

- package.json
- src/renderer/src/features/chat/components/chat-page.tsx
- src/renderer/src/features/chat/components/message-item/error-block.tsx
- src/renderer/src/features/chat/components/message-item/expandable-thinking-content.tsx
- src/renderer/src/features/chat/components/message-item/index.tsx
- src/renderer/src/features/chat/components/message-item/message-paper.tsx
- src/renderer/src/features/chat/components/message-item/streaming-message.tsx
- src/renderer/src/features/chat/types/message.ts
- src/renderer/src/shared/api/local-operator/types.ts
- src/renderer/src/shared/hooks/use-conversation-messages.ts
- src/renderer/src/shared/hooks/use-scroll-to-bottom.ts
Provide a brief overview of the changes introduced in this PR.
- This change addresses new feature implementation and refactoring (e.g., adding expandable thinking content for better user experience in chat messages).
- Key improvements include updating error messages for clarity, enhancing chat page scrolling logic, and introducing a new component for expandable thinking content.
Link any related issue or feature request (e.g., closes #123):
- Related: #... (No specific issues linked in the current context)
Describe the impact of these changes on the codebase:
- Does this change introduce any breaking changes? No breaking changes; updates are additive and improve UX without altering existing functionality.
- Are there any dependency updates? The version in package.json has been bumped …
> feat: Enhance chat UI with thinking content and error handling

- package.json
- src/preload/index.d.ts
- src/renderer/src/features/agents/components/agent-settings.tsx
- src/renderer/src/features/agents/components/chat-settings.tsx
- src/renderer/src/features/agents/components/general-settings.tsx
- src/renderer/src/features/agents/components/security-settings.tsx
- src/renderer/src/features/agents/components/system-prompt-settings.tsx
- src/renderer/src/features/chat/components/canvas/canvas-file-viewer.tsx
- src/renderer/src/features/chat/components/canvas/index.tsx
- src/renderer/src/features/chat/components/chat-content.tsx
- src/renderer/src/features/chat/components/message-item/action-block.tsx
- src/renderer/src/features/chat/components/message-item/error-block.tsx
- src/renderer/src/features/chat/components/message-item/file-attachment.tsx
- src/renderer/src/features/chat/components/message-item/image-attachment.tsx
- src/renderer/src/features/chat/components/message-item/index.tsx
- src/renderer/src/features/chat/components/message-item/video-attachment.tsx
- src/renderer/src/features/chat/types/canvas.ts
- src/renderer/src/features/chat/utils/file-types.ts
- src/renderer/src/features/chat/utils/get-file-name.ts
- src/renderer/src/features/onboarding/components/onboarding-dialog.tsx
- src/renderer/src/features/onboarding/components/onboarding-modal.tsx
- src/renderer/src/features/onboarding/components/steps/radient-choice-step.tsx
- src/renderer/src/shared/components/common/update-notification.stories.tsx
- src/renderer/src/shared/components/common/update-notification.tsx
- src/renderer/src/shared/hooks/use-oidc-auth.ts
- src/renderer/src/shared/store/canvas-store.ts
This PR introduces a new file viewer within the Canvas, allowing users to interact with various file types directly in the UI. It also includes several UI/UX improvements across the application and internal code organization enhancements.
- **Version Update:** `package.json` updated from `0.10.3` to `0.10.4`.
- **Preload API Extension:** `src/preload/index.d.ts` now includes `openFileNatively` for opening files with the OS's default application.
- **Agent Settings Refactor:** Refactored `SecuritySettings` and `SystemPromptSettings` components for better organization.
- **Advanced Chat Settings UI:** Introduced a collapsible "Advanced Chat Settings" section with new icons (`ChevronDown`, `ChevronRight` from `lucide-react`) and styling adjustments.
- **Canvas File Viewer:** Added a new …
> feat: Implement Canvas File Viewer and UI/UX Improvements

- package.json
- src/main/index.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/features/chat/components/canvas/canvas-file-viewer.tsx
- src/renderer/src/features/chat/components/canvas/canvas-variables-viewer.tsx
- src/renderer/src/features/chat/components/canvas/index.tsx
- src/renderer/src/features/chat/components/canvas/variable-form-dialog.tsx
- src/renderer/src/features/chat/components/message-input.tsx
- src/renderer/src/features/chat/components/message-item/file-attachment.tsx
- src/renderer/src/features/chat/components/message-item/image-attachment.tsx
- src/renderer/src/features/chat/components/message-item/video-attachment.tsx
- src/renderer/src/features/onboarding/hooks/use-onboarding-tour.ts
- src/renderer/src/shared/api/local-operator/agents-api.ts
- src/renderer/src/shared/api/local-operator/types.ts
- src/renderer/src/shared/components/common/file-actions-menu.tsx
- src/renderer/src/shared/hooks/use-agent-execution-variables.ts
- src/renderer/src/shared/store/canvas-store.ts
This PR adds comprehensive support for agent execution variables, including a new viewer component, form dialog for creation/editing, and associated API integrations. It also introduces file actions menu for better file handling in the canvas and general UI refinements.
- This is a new feature implementation and refactoring to enhance agent context management, making it easier to handle dynamic variables in conversations.
- Added a variables viewer with CRUD operations, integrated file actions for local files, and updated canvas components for better user interaction.
- Related: #... (Please link any relevant issues here)
- Does this change introduce any breaking changes? No breaking changes; it's additive to existing functionality.
- Are there any dependency updates? No new dependencies; …
> feat: Implement Execution Variable Management and UI Enhancements

- package.json
- src/renderer/src/features/chat/components/audio-recording-indicator.tsx
- src/renderer/src/features/chat/components/message-input.tsx
- src/renderer/src/features/chat/components/waveform-animation.tsx
- src/renderer/src/shared/api/local-operator/index.ts
- src/renderer/src/shared/api/local-operator/transcription-api.ts
- src/renderer/src/shared/api/local-operator/types.ts
This PR introduces speech-to-text capabilities into the chat message input, allowing users to record audio and have it transcribed into text. This feature enhances accessibility and user convenience.
- What does this change address? This is a new feature that provides an alternative input method for users, improving the overall user experience.
- What are the key improvements or modifications?
- **Audio Recording:** Added a microphone button to the chat input to start and stop audio recording.
- **Visual Indicators:** Implemented `AudioRecordingIndicator` with a pulsing dot and real-time waveform visualization during recording.
- **Transcription Processing:** Introduced `WaveformAnimation` for visual feedback while audio is being transcribed.
- **Transcription API Integration:** …
> feat: Implement Speech-to-Text Functionality in Chat Input

- .github/workflows/install-scripts-check.yml
- .gitignore
- build/entitlements.mac.plist
- package.json
- scripts/setup-python-resource.sh
- src/main/backend/scripts/macos-install-script.sh
- src/main/index.ts
- src/renderer/src/features/chat/components/message-input.tsx
- src/renderer/src/features/installer/components/feature-carousel.tsx
- src/renderer/src/features/onboarding/components/steps/default-model-step.tsx
This PR improves the Electron application's build process by adding multi-architecture support for Python resources (x86_64 and aarch64), updates entitlements for audio input, and enhances UI elements such as zoom controls and audio recording features. It ensures better compatibility on Apple Silicon devices and refines the user experience for transcription-related functionality.
- What does this change address? This is a new feature and refactoring to support diverse hardware architectures and improve UI interactions.
- What are the key improvements or modifications?
- **Multi-Architecture Python Setup:** Updated scripts to handle both x86_64 and aarch64 Python builds, including dynamic detection in installation scripts.
- **Audio Input Entitlements:** Added …
> feat: Enhance Multi-Architecture Support and UI for Transcription UX

- build/entitlements.mac.plist
- package.json
- pnpm-lock.yaml
- src/main/backend/scripts/linux-install-script.sh
- src/main/backend/scripts/macos-install-script.sh
- src/main/backend/scripts/windows-install-script.ps1
- src/renderer/src/features/chat/components/canvas/canvas-file-viewer.tsx
- src/renderer/src/features/chat/components/canvas/code-editor.tsx
- src/renderer/src/features/chat/components/canvas/html-preview.tsx
- src/renderer/src/features/chat/components/message-input.tsx
- src/renderer/src/features/chat/components/message-item/file-attachment.tsx
- src/renderer/src/features/chat/components/message-item/video-attachment.tsx
- src/renderer/src/features/command-palette/components/command-palette.tsx
- src/renderer/src/shared/components/common/confirmation-modal.tsx
- src/renderer/src/shared/components/common/file-actions-menu.tsx
This PR introduces comprehensive recording capabilities (audio and video) to the UI, along with cross-platform FFmpeg installation logic for Electron. It also includes various UI/UX improvements related to file viewing, editing, and general application usability.
- What does this change address? This is a new feature implementation and refactoring to enable multimedia recording and enhance the overall user interface and development experience.
- What are the key improvements or modifications?
- **Recording UI:** Integrated audio and video recording functionality directly into the chat message input, with corresponding UI elements (start/stop/confirm/cancel buttons).
- **Cross-Platform FFmpeg Installation:** Added robust scripts for Linux, macOS, and Windows to automatically download and …
> feat: Implement Recording UI and Cross-Platform FFmpeg Installation

- package.json
- src/main/index.ts
- src/renderer/index.html
- src/renderer/src/features/chat/components/message-input.tsx
- src/renderer/src/features/chat/components/message-item/action-block.tsx
- src/renderer/src/features/chat/components/message-item/audio-attachment.tsx
- src/renderer/src/features/chat/components/message-item/index.tsx
- src/renderer/src/features/chat/components/message-item/message-controls.tsx
- src/renderer/src/features/chat/components/message-item/message-paper.tsx
- src/renderer/src/features/chat/components/message-item/text-selection-controls.tsx
- src/renderer/src/shared/api/local-operator/index.ts
- src/renderer/src/shared/api/local-operator/speech-api.ts
- src/renderer/src/shared/api/local-operator/static-api.ts
- src/renderer/src/shared/api/local-operator/types.ts
- src/renderer/src/shared/store/speech-store.ts
This PR introduces comprehensive Text-to-Speech (TTS) capabilities to the Local Operator UI, allowing users to generate speech from agent messages and selected text. It includes new UI components for audio playback, integrates with the backend's new speech API, and enhances user interaction with new keyboard shortcuts and controls.
- What does this change address? This is a new feature implementation to enable audio output for agents and improve language interaction within the UI.
- What are the key improvements or modifications?
- **TTS Playback Controls:** Added play/pause, stop, and replay functionality for agent messages, with caching of audio blobs.
- **Text Selection to Speech:** Implemented a new control that appears on text selection, allowing users to generate and play speech for …
> feat: Implement Text-to-Speech (TTS) UI and Enhanced Audio Playback

- package.json
- src/renderer/src/features/chat/components/chat-page.tsx
- src/renderer/src/features/chat/components/message-item/index.tsx
- src/renderer/src/features/chat/components/message-item/message-paper.tsx
- src/renderer/src/features/chat/components/message-item/streaming-message.tsx
- src/renderer/src/features/chat/components/messages-view.tsx
- src/renderer/src/shared/hooks/use-message-input.ts
- src/renderer/src/shared/hooks/use-scroll-to-bottom.ts
- src/renderer/src/shared/hooks/use-streaming-message.ts
This pull request addresses several bugs related to real-time message streaming to make the user experience more robust and reliable.
- **Robust Streaming State Management**: The logic for determining when a message is actively streaming has been significantly improved. By using a centralized store (`useStreamingMessagesStore`) and more sophisticated checks, the application now more accurately tracks the completion state of a message, fixing bugs where the streaming indicator would disappear prematurely or persist incorrectly.
- **Elimination of Race Conditions**: The code now uses `requestAnimationFrame` for scrolling and `setTimeout` delays for completion callbacks and data refetching. This ensures that UI updates and state changes are fully processed before subsequent actions are …
> fix: Improve message streaming reliability
